### ISSUE TITLE
Fastq-Filterer does not consistently create the stats file

### ISSUE THREAD

**Issue by tcezard** [EdinburghGenomics/Fastq-Filterer#10]
Several pipeline runs fails because few of the run element had not stats file creates despite the options being provided on the command line.
I could not see errors in any of the logs available beyond the lack of stats file

**Comment by mwhamgenomics** [comment]
This seems to occur randomly when running many filter jobs at the same time through a resource manager. `strace` doesn't say much, so trying it with Valgrind.

**Comment by mwhamgenomics** [comment]
It turns out that this problem is not due to any fault in Fastq-Filterer, but is caused by incorrect handling of background processes under Slurm. In brief, we need to:

- kick off fastq filterer and two pigz instances as three child processes
- after kicking off each one, use `$!` to capture the pid
- `wait` on each pid and use `$?` to capture an exit status
  - this still works after a pid has completed because it's still registered as a child process
